### ISSUE TITLE
bug: Video playback does not work

### ISSUE THREAD

**Issue by GitHubovec559** [d4n3436/revanced-patches-android5#22] opened 2024-03-09 15:26 UTC
### Type

Error while patching

### Bug description

Video playback does not work when you click on it (when you log in to your account, without logging in everything works). Instead it flashes gray around the video and that's it, nothing else happens

### Steps to reproduce

Just log into your Google account via YouTube Revanced and click on the video, it will not open

### Device Environment

Android 5.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment] 2024-03-09 16:42
Duplicate of #21.

**Closed as not planned by d4n3436** 2024-03-09 16:42 UTC
Labels: bug

**Comment by testermania** [comment] 2024-07-07 11:39
@d4n3436 hey dude Which version should I use? revanced-cli v3.1.1 or latest 4.6.0 for new patch java -jar revanced-cli.jar

[auto-cli](https://github.com/taku-nm/auto-cli) use oldest versions.

**Comment by d4n3436** [comment] 2024-07-07 16:49
> @d4n3436 hey dude Which version should I use? revanced-cli v3.1.1 or latest 4.6.0 for new patch java -jar revanced-cli.jar
> 
> [auto-cli](https://github.com/taku-nm/auto-cli) use oldest versions.

@testermania Use v3.1.1. If you have any other questions please open a new issue instead.
